### PR TITLE
Run scrutinizer upon execution

### PR DESCRIPTION
**Pull request by dimitrisnl**
Change-type: minor

### CODE REVIEW

**Comment by dimitrisnl** [comment]
hey @jviotti , I need your help on this one.

I'm trying to scan [Balena-dash](https://github.com/balena-io-projects/balena-dash) by using `npx landr@the-latest-version-of-this-PR`.

Anytime there is an issue, I patch it either in scrutinizer or in landr.

I use `NPX` since the project isn't an NPM one, so I can't add Landr it as a devDependency. Furthermore, if I created one, it would take the wrong data (like the version).

Here's the problem. Landr doesn't run in the context of the repository that way.

```
[Error: ENOENT: no such file or directory, scandir '/var/folders/bp/ny_pjktx48scj3zqz81hry4m0000gn/T/scrutinizer_5677WZQJV6Jxs82j/blog'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/var/folders/bp/ny_pjktx48scj3zqz81hry4m0000gn/T/scrutinizer_5677WZQJV6Jxs82j/blog'
}
```

An obvious problem when trying to scan _locally_ the repository.

Any ideas on how to treat non-npm repos? Is using `npx` out of the question?

**Comment by jviotti** [comment]
@dimitrisnl I don't think we should use `npx` for non npm repos. Why not globally installing the version of Landr you need and running that, or have Landr cloned in another directory and call it from the right place directly?

**Comment by jviotti** [comment]
@dimitrisnl I don't think we want people to install Landr as a dev dependency. They would download the Landr CLI somehow (maybe npm or a standalone binary from GitHub Releases) and run it against their repo.

**Comment by dimitrisnl** [comment]
@jviotti It makes sense how to download it because I'm relying on scrutinizer's local mode. I'm going to try.

**Comment by dimitrisnl** [comment]
@jviotti Even if they install Landr globally it has the same problem as NPX

```
[Error: ENOENT: no such file or directory, scandir '/var/folders/bp/ny_pjktx48scj3zqz81hry4m0000gn/T/scrutinizer_4795UL6F4yStDdQM/blog'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/var/folders/bp/ny_pjktx48scj3zqz81hry4m0000gn/T/scrutinizer_4795UL6F4yStDdQM/blog'
}
```

The execution context isn't relative to the repo we "scrutinize"

**Comment by jviotti** [comment]
@dimitrisnl I don't think I'm understanding the problem very well. Can we discuss it in today's check-in so you can show me?

**Pull request merged**
