### PR TITLE
Add Storybook

### PR DESCRIPTION
**Pull request by dimitrisnl**
Change-type: minor

Here's a working version with the homepage + the standalone sections.
I have set up a working Netlify project that auto-deploys storybook.

https://deploy-preview-219--landr-storybook.netlify.com/?path=/story/*

Next-up: Get all the possible combinations. This PR adds the basic skeleton.

### CODE REVIEW

**Comment by dimitrisnl** [comment]
Need to

- Add the sections as a story
- Figure out the data flow so that we can populate these stories

**Comment by dimitrisnl** [comment]
Screen Shot 2019-08-19 at 7 01 49 PM

Alright, I need to get figure out how to pass the data. Maybe exposing the render function isn't the best option. I have to get the combinations out there.

cc @jviotti

**Comment by dimitrisnl** [comment]
Need to

- Fix fonts
- Deploy storybook as a separate project

**Comment by dimitrisnl** [comment]
Here's a preview https://5d63a26f9acb4d000a22bb03--landr-storybook.netlify.com/?path=/story/* 🎉

**Comment by dimitrisnl** [comment]
@jviotti 	Following the approach that tests do generates lots of unnecessary component variants. For example we test Jumbotron, FAQ or Motivation component for pages that don't have them.

How can I get only the needed components for each page?

**Comment by jviotti** [comment]
@dimitrisnl Ah, good point. I thought about potential solutions, but I think the best way is to not divide the storybook by pages, and but rather by component. Then, you can just keep track of the components you created (given the variant options) and avoid creating the exact same one twice.

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by dimitrisnl** [comment]
But these components depend on 1) The route, 2) The context that it runs

**Comment by dimitrisnl** [comment]
@jviotti 	I was thinking, dow e really want to show all the variants? We know the input already - by showing extra variants we don't gain much.

We could keep a single one, the one we will build and allow changing props right on the spot.

Showing variants mattered when we change the order of sections. If we only display the components it's insignificant.

**Comment by dimitrisnl** [comment]
As I followup I was thinking of getting a MVP out of it, just by importing the meta.json and wrap this up. It's meant to speed track the development process, and I'm afraid I'm overengineering it.

**Comment by dimitrisnl** [comment]
I think is is a good first version. Still need to figure out how to filter out invalid combinations but it will suffice for now.

**Pull request merged**
