### PR TITLE
Fix incorrect paths when navigating versioned docs

### PR DESCRIPTION
**Pull request by dimitrisnl**
Connects-to: #196
Change-type: minor
Signed-off-by: Dimitrios Lytras <dimitrios@balena.io>

### CODE REVIEW

**Comment by dimitrisnl** [comment]
Due to the paths containing strings like `0.1.1`, the versioned docs would fail to load. Using `0_1_1` instead.

**Comment by dimitrisnl** [comment]
update, this is a bug of `serve` that I use for the local server. Will update the PR accordingly.

**Comment by jviotti** [comment]
Can we use hyphen instead?

**Comment by dimitrisnl** [comment]
@jviotti 	Since it's an issue with the `serve` package, I don't think we should drop the dot format.

**Comment by jviotti** [comment]
Sound good

**Comment by dimitrisnl** [comment]
I could use the review now @jviotti 	 :D

**Pull request merged**
